# Generated by Django 4.2 on 2023-05-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('sketch_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'Sketch',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(max_length=32)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sketch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=1024)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
