# Generated by Django 4.2.1 on 2023-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2002-04-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tattoos_made',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
