# Generated by Django 4.2.1 on 2023-05-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sketch_description_sketch_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(default='accepted', max_length=32),
        ),
    ]
