# Generated by Django 4.2.1 on 2023-05-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_rate_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.session'),
            preserve_default=False,
        ),
    ]
