# Generated by Django 4.2.1 on 2023-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='user_photos'),
        ),
    ]
