# Generated by Django 4.2.1 on 2023-05-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_tattoos_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
