# Generated by Django 4.2.1 on 2023-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='session',
            name='employee',
        ),
        migrations.AddField(
            model_name='review',
            name='employee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='employee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
