# Generated by Django 4.2 on 2023-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
